### DISCUSSION TITLE
ESP32 daemon in toit for use with Pharo Smalltalk

### DISCUSSION THREAD

**Discussion by robvanlopik** [toitlang/toit#1512] [Show and tell]
Exposing the capabilities of a microcontroller for use on another computer with another programming language is not uncommon. Think of Firmata on Arduino, or PiGPIO on Raspberry Pi. In Pharo I have a [framework](https://github.com/robvanlopik/Pots) for this, using that kind of firmware. Having followed toit for over a year, I thought it was time to build another bridge. The daemon is written in toit, the other side is a driver for Pharo and communication is through MQTT. See my [repo](https://github.com/robvanlopik/toit-pharo). I hope somebody finds this useful, at least the idea; I must confess this is the first time in many years that I used a programming language other than smalltalk.

I want to add at least out-of-band messages like notifications of pin state changes.

BTW. Can someone point me to some documentation about the use of "assets" and especially how to create them?

**Comment by kasperl** [comment]
@robvanlopik Assets are briefly explained here: https://github.com/toitlang/toit#adding-container-assets.

**Reply by floitsch** [reply]
Also, we plan on porting [Artemis' specification file](https://github.com/toitware/artemis-releases#specification-file) to standard Toit.
This means that you could then just write a simple specification with the constants in it. Something like (once it's Yaml and not JSON):
``` yaml
containers:
  pharo-daemon:
    entrypoint: daemon.toit
    git: https://github.com/robvanlopik/toit-pharo.git
    properties:
      host: test.mosquitto.org
      port: 1883
      pins: [2, 4, ... ]
      output-pins: ...
      adc: [32,33,34,35,36,39]
      dac: [25, 26]
      i2c: [21, 22]
      sda: 21
      sdc: 22
```

Also planned is then a way to let Jaguar consume such a file. Like: `jag flash foo.specification`.

I can't say when we will get around to make that happen, but I think that would be neat.
